# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-19 05:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20161219_1103'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog',
            new_name='Book',
        ),
    ]
