# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-20 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_book_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='comment',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
    ]
