# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-21 06:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20161220_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=700, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='comment',
        ),
        migrations.AddField(
            model_name='comments',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Book'),
        ),
    ]
