# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-21 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20161221_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
    ]
