# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-23 05:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20161221_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
