# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-23 10:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_comment_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='total',
        ),
    ]
