# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-23 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=6)),
                ('mail_id', models.EmailField(max_length=300)),
                ('date_of_birth', models.DateField()),
            ],
        ),
    ]
